roles:
  - name: linux-system-roles.timesync
  - name: linux-system-roles.network
  - name: linux-system-roles.cockpit
  - name: linux-system-roles.selinux
  - name: linux-system-roles.postfix
  - name: linux-system-roles.journald
  - name: linux-system-roles.bootloader
  - name: linux-system-roles.crypto_policies
  - name: linux-system-roles.firewall
  - name: linux-system-roles.tuned
  - name: linux-system-roles.certificate
  - name: linux-system-roles.rhc
  - name: linux-system-roles.kernel_settings
  - name: linux-system-roles.metrics
  - name: linux-system-roles.tlog
  - name: linux-system-roles.podman
  - name: linux-system-roles.systemd
  - name: linux-system-roles.logging
  - name: theforeman.foreman_scap_client
collections:
  - name: ansible.posix
  - name: containers.podman
  - name: community.general
  - name: community.docker
  - name: community.dns
  - name: community.crypto
  - name: freeipa.ansible_freeipa
  - name: kubernetes.core
  - name: theforeman.foreman